# Generated by Django 5.0.3 on 2024-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
