# Generated by Django 5.0.3 on 2024-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='products',
            field=models.ManyToManyField(related_name='sizes', to='store.products'),
        ),
    ]
