# Generated by Django 5.0.3 on 2024-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_size_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
        migrations.AddField(
            model_name='size',
            name='sizes',
            field=models.CharField(blank=True, help_text='Enter available sizes separated by commas', max_length=100, null=True),
        ),
    ]
