# Generated by Django 5.0.3 on 2024-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_size_name_remove_size_products_products_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sizes',
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
