# Generated by Django 5.0.3 on 2024-04-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_products_sizes_alter_size_name_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
