# Generated by Django 5.0.3 on 2024-04-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size'),
        ),
    ]
